# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/contraint.xdc

# Block Designs: bd/x4_bd/x4_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==x4_bd || ORIG_REF_NAME==x4_bd} -quiet] -quiet

# IP: bd/x4_bd/ip/x4_bd_processing_system7_0_0/x4_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==x4_bd_processing_system7_0_0 || ORIG_REF_NAME==x4_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/x4_bd/ip/x4_bd_axi_bram_ctrl_0_0/x4_bd_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==x4_bd_axi_bram_ctrl_0_0 || ORIG_REF_NAME==x4_bd_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/x4_bd/ip/x4_bd_blk_mem_gen_0_0/x4_bd_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==x4_bd_blk_mem_gen_0_0 || ORIG_REF_NAME==x4_bd_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/x4_bd/ip/x4_bd_axi_smc_0/x4_bd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==x4_bd_axi_smc_0 || ORIG_REF_NAME==x4_bd_axi_smc_0} -quiet] -quiet

# Block Designs: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/bd_aabe.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_1/bd_aabe_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_2/bd_aabe_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_3/bd_aabe_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_4/bd_aabe_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_5/bd_aabe_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_6/bd_aabe_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_7/bd_aabe_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_8/bd_aabe_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_9/bd_aabe_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_10/bd_aabe_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_11/bd_aabe_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_12/bd_aabe_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/x4_bd/ip/x4_bd_rst_ps7_0_100M_0/x4_bd_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==x4_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==x4_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/x4_bd/ip/x4_bd_radar_ctrl_top_0_0/x4_bd_radar_ctrl_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==x4_bd_radar_ctrl_top_0_0 || ORIG_REF_NAME==x4_bd_radar_ctrl_top_0_0} -quiet] -quiet

# XDC: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_processing_system7_0_0/x4_bd_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==x4_bd_processing_system7_0_0 || ORIG_REF_NAME==x4_bd_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_blk_mem_gen_0_0/x4_bd_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_1/bd_aabe_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_5/bd_aabe_s00a2s_0_ooc.xdc

# XDC: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_6/bd_aabe_sarn_0_ooc.xdc

# XDC: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_7/bd_aabe_srn_0_ooc.xdc

# XDC: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_8/bd_aabe_sawn_0_ooc.xdc

# XDC: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_9/bd_aabe_swn_0_ooc.xdc

# XDC: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_10/bd_aabe_sbn_0_ooc.xdc

# XDC: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/bd_0/ip/ip_11/bd_aabe_m00s2a_0_ooc.xdc

# XDC: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/ooc.xdc

# XDC: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==x4_bd_axi_smc_0 || ORIG_REF_NAME==x4_bd_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/ip/x4_bd_rst_ps7_0_100M_0/x4_bd_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==x4_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==x4_bd_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: C:/Users/17392/x4_fpga_radar/x4_fpga_radar.gen/sources_1/bd/x4_bd/x4_bd_ooc.xdc
